:title: Configuring Identity Credential Issuance in Keycloak over OpenID4VCI
:date: 2025-10-21
:publish: false
:author: Rodrick Awambeng, Forkim Enjeckayang, Ingrid Kamga, Bertrand Ogen
:summary: Keycloak implements OpenID for Verifiable Credential Issuance (OpenID4VCI), enabling users to be issued verifiable credentials as a digital proof of their identity. Several components need to be consistently configured to enable this functionality, from realms to clients and credential types via client scopes.

== Verifiable Credentials (VCs) and OpenID for Verifiable Credential Issuance (OpenID4VCI)

Verifiable Credentials (VCs) are a digital representation of credentials that can be cryptographically verified. They enable secure and privacy-preserving sharing of information between parties. VCs are designed to be tamper-evident and can be issued, held, and presented by individuals or entities. From a conceptual standpoint, Keycloak, as an identity and access management solution, can therefore be set to issue VCs to users as a standalone digital proof of their identity. Such may also be referred to as Identity Credentials.




https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html[OpenID for Verifiable Credential Issuance] (OpenID4VCI) is a protocol that extends the OpenID Connect framework to facilitate the issuance of verifiable credentials. It provides a standardized way for issuers to issue VCs to holders, allowing for interoperability and secure communication between different systems.
